### ISSUE TITLE
Update russian translate

### ISSUE THREAD

**Issue by IgorPolyakov** [ubports/indicator-keyboard#7] opened 2018-11-02 07:24 UTC
Indicator-keyboard haven't update russian translate.

But it has 100% [translate](https://translate.ubports.com/projects/ubports/indicator-keyboard/ru/#overview)

- Device: hammerhead (nexus 5)
- Channel: dev
- Build: 2018-10-30/2

![screenshot20181102_140221228](https://user-images.githubusercontent.com/2613581/47899059-e86c0500-deaa-11e8-9008-661b7d8f0628.png)

**Comment by Flohack74** [comment] 2018-11-07 19:52
Duplicate of #8

**Closed as completed by Flohack74** 2018-11-07 19:52 UTC
Labels: duplicate
